---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - wget
    - yum-utils
    - git
    - python3
    - python3-pip
    - lvm2
    - devider-mapper-persistent-data

- name: Add docker repository
  yum_repository:
    name: docker-ce-stable
    baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
    enable: yes

- name: Add gpg key
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    
- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest

- name: Start docker
  service:
    name: docker
    state: started
    enabled: yes

- name: add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  notify: restart docker

- name: Install docker python module
  pip:
    name: docker-py
    state: latest
    executable: pip3
  