---
# tasks file for webapp
- include_tasks: "docker-ubuntu.yml"
  when: ansible_distribution == "Ubuntu"
## add another distributions

- name: Copy templatefile
  template:
    src: index.html.j2
    dest: "/home/{{ ansible_user }}/index.html"
- name: Start apache container
  docker_container:
    name: webapp
    image: httpd:latest
    state: started
    ports:
      - "8082:80"
    volumes:
      - "/home/{{ ansible_user }}/index.html:/usr/local/apache2/htdocs/index.html"

    
