apiVersion: apps/v1
kind: Deployment
metadata:
    name: wordpress
    namespace: wp-k8s
    labels:
        app: wordpress
spec:
    replicas: 1
    selector:
        matchLabels:
            app: wordpress
            tier: frontend
    template:
        metadata:
            labels:
                app: wordpress
                tier: frontend
        spec:
            containers:
              - image: wordpress:6.2.1-apache
                name: wordpress
                env:
                  - name: WORDPRESS_DB_HOST
                    value: wordpress-mysql
                  - name: WORDPRESS_DB_USER
                    value: admin
                  - name: WORDPRESS_DB_PASSWORD
                    value: password
                  - name: WORDPRESS_DB_NAME
                    value: wordpress
                ports:
                  - containerPort: 80
                    name: wordpress
                volumeMounts:
                  - name: wordpress-persistent-storage
                    mountPath: /var/www/html
            volumes:
              - name: wordpress-persistent-storage
                persistentVolumeClaim:
                  claimName: wordpress-pv-claim