apiVersion: v1
kind: Secret
metadata:
  name: wp-secret
  namespace: k8s-wordpress
  labels:
    app: wordpress
    tier: frontend
type: Opaque
data:
  db_user: YWRtaW4= #admin
  db_pass: cGFzc3dvcmQ= #password
  db_name: d29yZHByZXNz #wordpress
  