apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    tier: database
  namespace: k8s-wordpress
type: Opaque
data:
  root_pass: cm9vdA== #root
  db_name: d29yZHByZXNz #wordpress
  db_user: YWRtaW4= #admin
  db_pass: cGFzc3dvcmQ= #password