apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  namespace: wp-k8s
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: 10.96.0.11