apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql
    tier: database
  namespace: k8s-wordpress
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
    tier: database
  type: ClusterIP