# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = false

  # Provision SSH key
  config.vm.provision "shell" do |s|
    ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    s.inline = <<-SHELL
    mkdir -p /home/vagrant/.ssh
    echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
    chmod 600 /home/vagrant/.ssh/authorized_keys
    SHELL
  end

  # Define centos vm
  config.vm.define "centos" do |centos|
    centos.vm.box = "bento/centos-7.1"
    centos.vm.network "private_network", type: "static", ip: "192.168.56.53" #192.168.56.103
    centos.vm.hostname = "centos-server"
    centos.vm.provider "virtualbox" do |v|
      v.name = "centos"
      v.memory = 4096
      v.cpus = 2
    end
  end

  #define ubuntu-vm
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-24.04"
    ubuntu.vm.network "private_network", type: "static", ip: "192.168.56.52"
    ubuntu.vm.hostname = "ubuntu-server"
    ubuntu.vm.provider "virtualbox" do |v|
      v.name = "ubuntu"
      v.memory = 4096
      v.cpus = 2
    end
  end

end